version: 0.2
phases:
  install:
    commands:
    - export AWS_REGION="us-east-1"
    - export RDS_DATABASE_NAME="ntier"
    - export RDS_USER_NAME="admin"
    - export RDS_PASSWORD="password"

    - aws rds create-db-instance --db-instance-identifier ${RDS_DATABASE_NAME} --db-name ${RDS_DATABASE_NAME} --vpc-security-group-ids sg-075decb0f531d1ee9 --db-subnet-group-name default-vpc-05858b9e73e251b3a --allocated-storage 20 --db-instance-class db.t2.small --engine mysql --master-username ${RDS_USER_NAME} --master-user-password ${RDS_PASSWORD} --region ${AWS_REGION}

    - aws rds wait db-instance-available --db-instance-identifier ${RDS_DATABASE_NAME}
    
    - echo "installing mysql client"
    - yum install -y mysql
    - echo "mysql client instalation done "
    - echo "connecting to the database and adding data"
    - mysql --host=ntier.cvvkrojoestg.us-east-1.rds.amazonaws.com --port=3306 --user=admin --password=password ntier -e "SHOW TABLES; CREATE TABLE users (name VARCHAR(20), email VARCHAR(20)); INSERT INTO users (name, email) VALUES (user1, user1@gmail.com); SELECT * FROM users"
